### ISSUE TITLE
UTF8 by default possible?

### ISSUE THREAD

**Issue by alvipeo** [madskristensen/AddAnyFile#10]
Great extension but is it possible to create a file with UTF8 by default?

**Comment by madskristensen** [comment]
Fixed

**Comment by alexandretperez** [comment]
It's not working for me.

When I create a new file this is encoded as "Western European (Windows) - Codepage 1252", then I need manually save it as "Unicode (UTF-8 with signature) - Codepage 65001".

Here is the products version:
Visual Studio Community 2015 (Update 2) 14.0.25123.00
Plugin version: 3.4.101

**Comment by madskristensen** [comment]
The weird part about this is that it is saved with `new UTF8Encoding(false)` so it appears that it's just Visual Studio that can't figure it out since there is no BOM
