### ISSUE TITLE
File-scoped namespace preferences are applied in the project root, but not in folders.

### ISSUE THREAD

**Issue by jhigh2000** [madskristensen/AddAnyFile#102]
Extension v4.0.171 - https://www.vsixgallery.com/extension/d48e8f25-661b-4970-8b66-03f051ba5fc3

**Minimal Repo:**

File...New Project...Console Application.

In the project root: 
SHIFT+F2, Foo.cs --> File created and file-scoped namespaces preferences applied.
SHIFT+F2, Folder/Bar.cs --> File created in Folder/and file-scoped namespaces not applied. Same behavior if "Folder" is manually created first.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/138398/146791558-cccad063-1a29-42c6-8619-08b26e117850.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/138398/146791594-9b5e5019-8f8d-4600-a568-685094a2b707.png">
<img width="819" alt="image" src="https://user-images.githubusercontent.com/138398/146791618-b9c903c4-90c3-4ed6-9c54-75427f0467dc.png">
<img width="924" alt="image" src="https://user-images.githubusercontent.com/138398/146791659-c1d112b1-fac3-4d6f-866f-e3bb85cab759.png">

**Comment by timheuer** [comment]
Weird, I can confirm this as well @madskristensen but I thought we both verified this :-(
