### ISSUE TITLE
Git does not consider files as added in VS2015

### ISSUE THREAD

**Issue by alvipeo** [madskristensen/AddAnyFile#11]
If extension is used the added file does not picked up by source control in VS2015. In other words these files will never be in repo IF not re-added manually.

Could be VS2015 issue and not the extension's, I'm not sure.

**Comment by madskristensen** [comment]
Are you using TFS or Git?

**Comment by alvipeo** [comment]
Git

**Comment by madskristensen** [comment]
It works fine for me. I can't reproduce this

**Comment by madskristensen** [comment]
Any update?

**Comment by alvipeo** [comment]
Works for me too now!
