### ISSUE TITLE
Add VS 2022 Support

### ISSUE THREAD

**Issue by renato04** [madskristensen/AddAnyFile#116]
### Description
The extension does not run on VS 2022

### Steps to reproduce
1. Install VS 2022
2. Install AddAnyFile

**Expected behavior:** [What you expected to happen]
The extension work properly
**Actual behavior:** [What actually happened]

![image](https://user-images.githubusercontent.com/5497267/160821604-64f50b1b-c31e-40f3-9c9a-accbbbc88746.png)

**Comment by Khaon** [comment]
Hello,
you need to use this package.
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.AddNewFile64

**Comment by renato04** [comment]
Thank you @Khaon
