### ISSUE TITLE
Can we add sealed classes by default?

### ISSUE THREAD

**Issue by voroninp** [madskristensen/AddAnyFile#123]
Hi, your cool extension is very nice, but is it possible to configure it, so it creates `sealed` classes?

**Comment by nf313743** [comment]
You can achieve this using templates:

> Create a .templates folder at the root of your project. The templates inside this folder will be used alongside the default ones.

Create a .cs.txt file in .templates similar to this:
https://github.com/madskristensen/AddAnyFile/blob/master/src/Templates/.cs.txt

**Comment by voroninp** [comment]
Thanks. It's also possible to extend the set? For example, if file is named `BlaBlaTests.cs` then template for xunit test is used.

**Comment by voroninp** [comment]
Nevermind, found answer [here](https://github.com/madskristensen/AddAnyFile)
