### ISSUE TITLE
Mads: I reported this to MS VS Team but here is what I found.

### ISSUE THREAD

**Issue by SFC-Sarge** [madskristensen/AddAnyFile#143]
## Add New File Feature in 17.5 does not work in VSIX Project!

Just create a VSIX extension project then try to use the new Add New File Feature. (Add, New Item) The Dialog with the new feature seen here does not exist in a VSIX extension project:
![AddNewItemDialog](https://user-images.githubusercontent.com/67446778/222506091-1d490b90-a7fa-46c9-bdca-20b6610babeb.png)

So, you cannot add a new file using this method by just typing a file name and extension. You are limited to the original dialog and have to select a template.

**Comment by chucker** [comment]
Probably a duplicate of #135.

You probably want to reassign the shortcut: https://github.com/madskristensen/AddAnyFile/issues/135#issuecomment-1326282662 (VS itself steals the shortcut away from this extension).

**Comment by SFC-Sarge** [comment]
Not using the shortcut, using the right click menu to select Add then new Item. Works in non-VSIX projects just fine but in VSIX projects you do not get the dialog above, but the old standard dialog and that dialog has no option to get to this dialog either.  but in a non-VSIX this dialog shows by default and the old standard dialog has the option to return to this dialog.

**Comment by SFC-Sarge** [comment]
OK, I removed the AddQuickFile shortcut SHIFT-F2, then I changed the AddQuickFile shortcut to CTRL-SHIFT-A and now it works even in the Right Click Menu. Strange behavior that the Right Click Menu requires the AddQuickFile shortcut be set to something else to work.
