### ISSUE TITLE
Changed behavior in vs2022

### ISSUE THREAD

**Issue by endlessMagic** [madskristensen/AddAnyFile#145]
**Describe the bug**
When pressing shift-f2, the extension will use the folder of the current file for the location of the new file in vs2019. But in vs2022 (64bit version), it uses another location (I don't know why choosing that path, looks like a project root path) for creating new file, which is very annoying.

**To Reproduce**
1. After installing the extension, navigate to a file will deeper folder structure.
2. Just press shift-f2, vs2022 will choose a weird location for creating the new file.

**Expected behavior**
Extension should have the same behavior in both vs2019 and vs2022. And ideally use the behavior of vs2019, as I've no clue why the current rule for determining the location of new file.

**Comment by chucker** [comment]
You’re probably in VS’s new built-in feature rather than the extension. Try reassigning the shortcut: https://github.com/madskristensen/AddAnyFile/issues/135#issuecomment-1326282662

**Comment by endlessMagic** [comment]
Thx @chucker  :)
