### ISSUE TITLE
Shorthand for adding multiple files

### ISSUE THREAD

**Issue by ariesdane** [madskristensen/AddAnyFile#16]
Add support for adding multiple files from the dialog if the user provides a comma separated list of file names. This would be especially helpful for SPA components that leverage.html templates with .js view models.

Example 1:

IEmployee.cs, Employee.cs

Gold Plated version:

SPA / MVVM style components often follow the pattern of (component-name<.html|.js>), in this situation users would likely prefer a shorthand syntax for specifying just the extensions.

Example 2: 

widget1[.js][.html]    // creates widget.js and widget.html
widget1[js][html]  // works the same - leading period is optional

Example 3

webform1[.aspx][.aspx.cs] // creates webform1.aspx and webform1.aspx.cs
webform1[aspx][aspx.cs] // works the same - leading period is optional
webform1.aspx[cs]  // only creates webform1.apsx.cs

Example 4

widget1[js][html], widget2[js][html], site.css    // creates widget1.js, widget1.html, widget2.js, widget2.html, and site.css

**Comment by madskristensen** [comment]
Awesome idea. I love it

**Comment by ariesdane** [comment]
I'm going to try to follow the contribution guide as best as possible and take a hack at this. I'll try to follow your code style and keep changes to the bare minimum to implement all or part of this feature request.

**Comment by madskristensen** [comment]
Globbing syntax would look like `filename.(js,html,css)`

**Comment by ariesdane** [comment]
Understood. I'll research globbing syntax and implement accordingly.


________________________________
