### ISSUE TITLE
Folder already exists exception

### ISSUE THREAD

**Issue by PavelPikat** [madskristensen/AddAnyFile#18]
I tried using this pluing in Node.js project in VS2015, but it throws "Folder already exists" error when I tried to create a new JavaScript file. 

What I do is:
1. Right click on "app" folder, select Add new empty file
2. The dialog shows app/[enter filename text field]
3. I type the filename, for example "test.js" and click OK
4. It throws an error telling me that it can't create test.js inside of my "app" folder, because this folder already exists??

**Comment by PavelPikat** [comment]
*update:

This only happens with .js files. I juyst tried adding .html, and it works fine.

**Comment by madskristensen** [comment]
Thanks for the bug report. Looking at it now

**Comment by madskristensen** [comment]
Issue fixed. Please help verify the fix in the latest CI build here http://vsixgallery.com/extension/2E78AA18-E864-4FBB-B8C8-6186FC865DB3/
