### ISSUE TITLE
Error Message when creating new file

### ISSUE THREAD

**Issue by NTTAKR** [madskristensen/AddAnyFile#19]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: 2.4.72

### Description
When I try to create a new file and press Shift-F2, I get a dialog to input the name of the file. 
I input a standard filename with extension ".cs", then an error message pops up: 

"Could not create test.cs"
"Falscher Parameter. (Ausnahme von HRESULT: 0x80070057 (E_INVALIDARG))"

Translatet this means: 
"Wrong parameter. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))"

After clicking OK in the error message dialog box you can validate, that the file is created in contrast to the message of the error dialog. 

### Steps to recreate
1. Select any folder
2. Press Shift-F2
3. input any filename
4. Press OK
5. Get Error message
6. Validate that file is created and added to git in spite of the error message

### Current behavior
Error message is displayed for each creation of a file

### Expected behavior
No error message is displayed.

**Comment by madskristensen** [comment]
Thanks for the bug report. What type of project are you seeing this in? ASP.NET WebForms, C++, Cordova or...?

**Comment by NTTAKR** [comment]
Hi Mads,

I tried it in my current project, which is a ASP.NET Webforms project

Thanks for the quick reply.

Best regards,
  Andreas Kroll

NTT-SolutionWare GmbH
Andreas Kroll
Am Hang 1G
40822 Mettmann
Germany

Tel:      +49 (2104) 175 7590
Fax:      +49 (2104) 175 7591
Mobil:   +49 (151) 5288 2476

Sitz der Gesellschaft:             Mettmann                               Bank / BLZ / Konto:                 VR-Bank Mainz / 550 604 17 / 68470
Handelsregisternummer:       HRB 21698                             IBAN:                                     DE47 5506 0417 0000 0684 70
Amtsgericht:                           Wuppertal                              BIC:                                        GENODE51MZ2
Geschäftsführer:                    Andreas Kroll                         Kontoinhaber:                          NTT-SolutionWare GmbH

Von: Mads Kristensen [mailto:notifications@github.com]
Gesendet: Freitag, 11. März 2016 17:02
An: madskristensen/AddAnyFile <AddAnyFile@noreply.github.com>
Cc: Andreas Kroll <akr@ntt-sw.de>
Betreff: Re: [AddAnyFile] Error Message when creating new file (#19)


Thanks for the bug report. What type of project are you seeing this in? ASP.NET WebForms, C++, Cordova or...?

**Comment by madskristensen** [comment]
The fix should be in. Please help verify the fix by installing the CI build version from here http://vsixgallery.com/extension/2E78AA18-E864-4FBB-B8C8-6186FC865DB3/

**Comment by NTTAKR** [comment]
Thanks for the quick fix. After restarting VS2015 it works as expected!
Great work, it's a real timesaver.
