### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by kentcb** [madskristensen/AddAnyFile#22]
### Installed product versions
- Visual Studio 2015 Enterprise

### Description
After cloning and installing extensibility SDK, I can't actually build. A bunch of references aren't resolving, and I'm unsure where they should be coming from (I would have thought the SDK, but apparently not):

![image](https://cloud.githubusercontent.com/assets/1901832/13769404/4578b3a6-eacf-11e5-8358-aa3a20e823e5.png)

I noticed that at least some of this stuff is [on NuGet](https://www.nuget.org/packages/Microsoft.VisualStudio.Editor/), but they were not added as NuGet dependencies.

### Steps to recreate
1. Clone on fresh machine
2. Install extensibility SDK
3. Try to build

### Current behavior
Unable to build due to missing references.

### Expected behavior
Should be able to build.

**Comment by kentcb** [comment]
By manually editing the project file and remove explicit references, I was able to get the references to resolve from my GAC. Obviously it's using different versions to what you've got, and no idea if that's a problem or not. But I _can_ build and debug.

Any thoughts on why this is?

**Comment by madskristensen** [comment]
I have VS2012, VS2013 and VS2015 installed in my dev box. That could be why the version numbers don't align. Can you give an example of exactly what you changed to make it work?

**Comment by kentcb** [comment]
Sure. Here's what I did:

1. Unloaded the project.
2. Edited the project file.
3. For every reference that wasn't resolving, I deleted the `, Version=11.0.0.0` from each line, such as [this one](https://github.com/madskristensen/AddAnyFile/blob/master/src/AddAnyFile.csproj#L77)
4. Reloaded the project.

Doing this allowed VS to resolve _any_ version of those assemblies. Since I only have VS2015 installed, it resolved those installed with VS2015.

**Comment by kennethscott** [comment]
+1 - Exact same thing happened to me.

**Comment by sameera** [comment]
You can select all the offending assembly references in VS solution explorer at once (ctrl+click to select) and in the Property pane (press F4), set Specific Version to false.

**Comment by madskristensen** [comment]
@kentcb Can you try what @sameera suggested?

**Comment by kentcb** [comment]
@madskristensen apologies for the tardy response. I've been snowed under with other projects - just coming up for air for a little bit.

I can confirm that @sameera's suggestion works for me.
