### ISSUE TITLE
Add "Copy if newer" checkbox/dropdown

### ISSUE THREAD

**Issue by vorou** [madskristensen/AddAnyFile#26]
I often use the extension to add test files which needs to be copied to output dir. It's tedious to go to properties and switching "Copy to output directory" to "Copy if newer" for each new file. I though it would be nice to have a option right in the AddAnyFile dialog box.

What do you think?

PS: Oh, and thank you for the extension, it's really cool.

**Comment by madskristensen** [comment]
It seems very scenario specific. Let's see if this suggestion gets any upvotes

**Comment by madskristensen** [comment]
No upvotes, so closing the issue
