### ISSUE TITLE
Causing issues in SSDT projects

### ISSUE THREAD

**Issue by scottt732** [madskristensen/AddAnyFile#27]
### Installed product versions
- Visual Studio: 2015 Professiional
- This extension: Add New File 3.3

### Description
When adding new .sql files under (ex) dbo\Tables, the files get  created in the right place on the disk but end up at the root of the project as a 'miscellaneous file'.  This causes issues where files need to be manually deleted (as the project doesn't allow you to move them to fix it).  I get an error dialog when trying to move the file back into the right place.   This doesn't apply to just dbo\Tables ... Your extension seems to have  compatibility issues with SSDT entirely.

### Steps to recreate
1. Expand dbo, Tables and select the Tables node
2. Hit Shift-F2
3. Type Test.sql

### Current behavior
The file ends up at the root of the project and is treated as a 'miscellaneous file'.  On the disk, it is saved in the right place.

### Expected behavior
It should end up being treated the same as any other tables created through the Add New File dialog.

**Comment by madskristensen** [comment]
What type of project do you see this behavior in? Is it a special SQL database type project?

**Comment by scottt732** [comment]
![image](https://cloud.githubusercontent.com/assets/197019/15830890/9f2c4c64-2be8-11e6-81d1-474de831bc7d.png)

**Comment by madskristensen** [comment]
Great, just what I needed. Thanks

**Comment by madskristensen** [comment]
Unfortunately, the SSDT projects don't support file regular VS API for including a file to the project, so this is now something you'd have to do manually. At least the issue with getting the error dialog is fixed.

**Comment by scottt732** [comment]
Thanks for looking into this & the quick turnaround.  It's better that it refuses to work than try & fail, putting the project in a bad state.  One of those little things that burned me so infrequently that I never remembered not to use it.
