### ISSUE TITLE
Mixed EOL characters (CRLF / LF) when adding files 

### ISSUE THREAD

**Issue by mrahhal** [madskristensen/AddAnyFile#28]
### Installed product versions
- Visual Studio: 2015
- This extension: 3.3.98 (latest)

### Description
I've always thought it has been visual studio's fault but adding a new file normally doesn't produce this problem. This is what an added c# file looks like:

![capture](https://cloud.githubusercontent.com/assets/4404199/15924766/7c5c96fc-2e3c-11e6-927c-0ebb645ddd66.PNG)

You can see that the EOL chars are mixed.
I'm using [this extension](https://visualstudiogallery.msdn.microsoft.com/545e56a7-98d7-47f9-9d84-4681f2903060) to visualize EOL characters.

To reproduce simply try adding a c# file.

I usually directly close and open the file, visual studio will then tell me that the file has mixed EOL endings and offers help.

**Comment by BrainCrumbz** [comment]
We're experiencing the same.

**Comment by mrahhal** [comment]
@madskristensen OK not mixing anymore (v3.4) but the added file is still different from how the context menu's "Add new file" does it. It has LF EOL instead of CRLF for one thing. This made things even harder :sweat_smile:

**Comment by madskristensen** [comment]
@mrahhal weird, I see CRLF

**Comment by mrahhal** [comment]
Oh, really weird. I have CRLF configured in all places. I'll check a couple of things and come back.

**Comment by mrahhal** [comment]
@madskristensen I'm seeing LF every time even with new projects of all kinds.

Is there a certain template being used when adding the file? Maybe it's not always the same as the template being used by visual studio's new file dialog?

**Comment by mrahhal** [comment]
Maybe we can ensure CRLF EOL by replacing "LF" with "CRLF" [here](https://github.com/madskristensen/AddAnyFile/blob/64e799f2fd9890f6184ecffd60a13ec665e86f31/src/AddAnyFilePackage.cs#L147)? I'm not sure if this's a good idea though.

**Comment by madskristensen** [comment]
The templates are not the ones shipped in VS. See them here https://github.com/madskristensen/AddAnyFile/blob/master/src/Templates/.cs.txt

**Comment by madskristensen** [comment]
I guess we could replace "LF" with "CRLF" but the actual templates seems to already have "CRLF" line endings

**Comment by mrahhal** [comment]
Yes that's what I'm seeing also. I'm sure @BrainCrumbz will face the same problem if he updates. So I guess there's something unknown in play here.

**Comment by madskristensen** [comment]
Do you have any extensions installed that might change your line endings?

**Comment by mrahhal** [comment]
I don't have anything that would change the file upon creation. It seems to be created that way (no yellow bars or anything).

**Comment by mrahhal** [comment]
@madskristensen were you facing the mixed EOL problem? Because it seemed to be happening because you're formatting a document that contains LF in the first place (so the format actually changes only some of them for some reason).

**Comment by madskristensen** [comment]
Yes, I had that problem and it was caused by the call to Format Document that the extension did. Removing the call removed problem for me

**Comment by mrahhal** [comment]
Waiting for @BrainCrumbz to confirm, but it can't hurt to ensure CRLF instead of LF like we said, can it?

**Comment by BrainCrumbz** [comment]
Trying on a Windows 10 64bits machine. Extension v3.4.101. Creating `Dummy.cs` through Shift+F2.

* VS 2013 Community, in a C# classlibrary project. Creating file does not show any yellow bar warning by VS. So I guess that means line endings are uniform throughout the file. Line endings is **LF** only.

![programmer s notepad - dummy cs](https://cloud.githubusercontent.com/assets/3185573/15975575/68ed8a28-2f4e-11e6-8b67-ad105982d633.png)

* VS 2015 Community, in a C# Asp.Net Core project. Identical results. 

![programmer s notepad - dummy2015 cs](https://cloud.githubusercontent.com/assets/3185573/15975691/0d0b552c-2f4f-11e6-96b0-1d28561279a4.png)

**Comment by BrainCrumbz** [comment]
Just for a test, if in Programmer's Notepad I switch line endings to CR-LF, I do see the difference in file, which is flagged as modified.

![programmer s notepad - 2015 - crlf](https://cloud.githubusercontent.com/assets/3185573/15975760/6e54a9dc-2f4f-11e6-83bf-6bda2683403c.png)

**Comment by BrainCrumbz** [comment]
Pardon me if I say something obvious, I did not follow the whole exchange above: that LF line ending seems to perfectly match what's inside `.cs.txt` template:

![programmer s notepad - cs txt](https://cloud.githubusercontent.com/assets/3185573/15975860/ece5f8d2-2f4f-11e6-91a4-358fdbf88701.png)

**Comment by mrahhal** [comment]
@BrainCrumbz actually, I'm seeing that `.cs.txt` is using CRLF after cloning this.

**Comment by madskristensen** [comment]
It may be the setting in VS to normalize line endings

**Comment by BrainCrumbz** [comment]
Mmhhh... Watch out about tricks played by git when "unpacking" files on disk. I did "view raw" in browser and then downloaded file. 
BrainCrumbz Admin
> BrainCrumbz <
Happily softwarize your business
Il 10/Giu/2016 21:14, Mohammad Rahhal <notifications@github.com> ha scritto:@BrainCrumbz actually, I'm seeing that .cs.txt is using CRLF after cloning this.

**Comment by mrahhal** [comment]
I guess it doesn't really matter as long as you're consistent and you use git with the correct EOL config option, but since most of the things in VS use CRLF we should really just replace LF in the template [here](https://github.com/madskristensen/AddAnyFile/blob/64e799f2fd9890f6184ecffd60a13ec665e86f31/src/AddAnyFilePackage.cs#L147) before writing the file.

**Comment by mrahhal** [comment]
@madskristensen I was trying to fix this but I couldn't debug (a random exception with the load of a dll it seems). Have you decided on anything else or are we going the replace LF route? (would be really glad if we fix this asap :sweat_smile:)

**Comment by BrainCrumbz** [comment]
Cool! I'd like to try the newly built version but ... what happened to [nightly build link](http://vsixgallery.com/extension/27dd9dea-6dd2-403e-929d-3ff20d896c5e/)? It shows a basically empty page, only the frame is visible:

![no content](https://cloud.githubusercontent.com/assets/3185573/16015300/54e23b2a-3195-11e6-81c8-b646d7b6e5ee.png)

**Comment by mrahhal** [comment]
Yeah, me too.

**Comment by madskristensen** [comment]
Try again. The nightly site was down

**Comment by mrahhal** [comment]
@madskristensen the link to the nightly in the README.md goes to the blank page above. But when I used [the link from the homepage](http://vsixgallery.com/extension/2E78AA18-E864-4FBB-B8C8-6186FC865DB3/) it showed up.

**Comment by mrahhal** [comment]
Works great BTW :+1:

**Comment by BrainCrumbz** [comment]
* New version works: all CR-LF line endings, and VS does not complain when reopening file
* Link posted by @mrahhal works: http://vsixgallery.com/extension/2E78AA18-E864-4FBB-B8C8-6186FC865DB3/
* Link in README still does not work: http://vsixgallery.com/extension/27dd9dea-6dd2-403e-929d-3ff20d896c5e/

**Comment by madskristensen** [comment]
@BrainCrumbz the link on the readme should now work. Thanks
