### ISSUE TITLE
 The 'AddAnyFilePackage' package did not load correctly

### ISSUE THREAD

**Issue by miguellira** [madskristensen/AddAnyFile#30]
### Installed product versions
- Visual Studio: 2013 Ultimate
- This extension: 3.4.104

### Description
When opening a solution in Visual Studio 2013 I am presented with the dreaded `The 'AddAnyFilePackage' package did not load correctly.` error message.

### Steps to recreate
1. Install the VSIX
2. Open an existing solution

### Current behavior
When opening a solution in Visual Studio 2013 I am presented with the dreaded `The 'AddAnyFilePackage' package did not load correctly.` error message.

The ActivityLog.xml file contains the following entries:
```xml
  <entry>
    <record>803</record>
    <time>2016/06/13 19:45:59.336</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [AddAnyFilePackage]</description>
    <guid>{27DD9DEA-6DD2-403E-929D-3FF20D896C5E}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>804</record>
    <time>2016/06/13 19:45:59.336</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [AddAnyFilePackage]</description>
    <guid>{27DD9DEA-6DD2-403E-929D-3FF20D896C5E}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
```

### Expected behavior
Solution opens and package loads properly

**Comment by madskristensen** [comment]
Can you please try the latest [ci build](http://vsixgallery.com/extension/2E78AA18-E864-4FBB-B8C8-6186FC865DB3/) that should have a fix?

**Comment by gawelczyk** [comment]
I have just updated the extension.
Visual Studio Professional 2012 update 5

And I have the same error:
<entry>
    <record>435</record>
    <time>2016/06/26 11:57:51.722</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [AddAnyFilePackage]</description>
    <guid>{27DD9DEA-6DD2-403E-929D-3FF20D896C5E}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version = 12.0.0.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a' or one of its dependencies. You can not find the file specified.</errorinfo>
  </entry>

It worked without problems before update
