### ISSUE TITLE
Allow to add file anyplace

### ISSUE THREAD

**Issue by dehghani-mehdi** [madskristensen/AddAnyFile#31]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: Just added, so last version

### Description
Thanks for the Awesome extension.

### Current behavior
Now, If I was in folder A, and hit shift+F2, I can add files & folder to current folder. 

### Expected behavior
But I think will be better if you ignore current place and allow the user to create files & folder from root.

**Comment by madskristensen** [comment]
You can use `../` syntax when specifying file name
