### ISSUE TITLE
Encoding of added files

### ISSUE THREAD

**Issue by yakimovim** [madskristensen/AddAnyFile#32]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: Add New File, version 3.4.105

### Description
Your extension stores newly created files using UTF8 encoding WITHOUT "UTF8 identifier" (see file AddAnyFilePackage.cs, method WriteToDisk, line 159 now). But even if the file uses one of your templates Visual Studio can't correctly recognize the encoding of the file. It thinks it is the default encoding of the OS. When I add some text to the file which has different codes in UTF8 and Default encodings (e.g. "Привет") Visual Studio still saves this file using Default encoding. 

It is very annoying then I write .html pages or templates. Browser expects them in UTF8 (I state it in 'meta' tag) but actually encoding is different. And I have to manually re-save all my files in UTF8 encoding.

At the same time when I create a new file using standard Visual Studio means (Solution Explorer -> 
context menu -> Add -> New Item) it creates file using UTF8 encoding WITH "UTF8 identifier".

So I'd like to ask you if you can change "false" to "true" in the constructor of UTF8Encoding class in the WriteToDisk method of AddAnyFilePackage.cs (line 159 now). What do you think about it?

### Steps to recreate
1. Add a new file using your extension (e.g. .html file)
2. Add some text which will be saved using different codes in UTF8 and Default encodings (e.g. "Привет").
3. Save the file in Visual Studio.
4. The file is saved in Default encoding, not in UTF8.

### P.S.
Thank you for great extensions!

**Comment by uselesshasid** [comment]
I see the same issue. When creating a new file using VS it will be utf, but when creating using the Add New File extension it will be in ANSI
