### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by kentcb** [madskristensen/AddAnyFile#33]
### Installed product versions
- Visual Studio 2015 Enterprise
- Add New File 3.4.105
### Description

Customizations to Visual Studio's template files are ignored by Add New File because it has its own templates.
### Steps to recreate
1. Customize the C# class item template by following [these steps](http://stackoverflow.com/a/2072717/5380)
2. Create a new C# class file using the VS dialog and observe that the changes are present.
3. Create a new C# class file using Add New File and observe that the changes are not present.
### Current behavior

VS item templates are ignored.
### Expected behavior

Either VS item templates should be used, or Add New File should provide a means of customizing its templates.
### Workarounds

Fork the project, modify the built-in templates, and run a custom build of the extension. Not ideal for obvious reasons.

**Comment by sameera** [comment]
Back around v2.6 of this extension, I sent a PR that implemented support for VS Item Templates. The PR was merged but after few subsequent releases the code for VS Template support was dropped.

If you would like to use that behavior and don't mind losing features between 2.6 and now (and gain a few other features like automatic file extension inclusion based on project type), you can try the extension from my fork
https://github.com/sameera/AddAnyFile

If you need VS 2017 support, please pull from "dev" branch and build in VS 2017.

**Comment by martea** [comment]
This would be graet, if you can make it available so that you can use convension based names to resolve a template that is produced in every project.

if i create _Template_Service.cs when i create i file like MyCusotmService.cs it should resolve to that template.

this would mean that you can create lots of templates that would make producing context quicker.

**Comment by sameera** [comment]
The code in the above branch already has regex based template mappings and you can customize to what you want.

**Comment by Ackara** [comment]
Hey guys, I found that you can add your own templates as is (v3.5.134) by creating new files in the following folder _(the extension's installation path)_.

`%localappdata%\Microsoft\VisualStudio\15.0_f5f2761e\Extensions\3duco4g1.iyl\Templates`

The only problem is that when the extension updates, I believe my own templates will be removed _(correct?)_. Therefore I was wondering what if we extend the search for templates to an additional folder outside of the installation path ([Templatemap.cs](https://github.com/madskristensen/AddAnyFile/blob/master/src/Templatemap.cs)), ideally a folder of my choice. We can add said folder-path in the `Visual Studio > Tools > Option > File Nesting > General` dialog.


What do you guys think?

**Comment by GW-FUB** [comment]
Thanks @Ackara for the hint. That worked.

If you need to find the correct folder (there are a lot different), use the following:

1. Navigate to `%localappdata%\Microsoft\VisualStudio`
2. Go to the highest version folder (like 14.0, 15.0)
3. Go to the `Extensions` folder
4. Search for `AddAnyFile`. You should find e.g. the dll. You can navigate to it's folder through the right click menu (Open in explorer)
5. Navigate to the `Templates` folder
6. Edit the templates

**Comment by jasdefer** [comment]
I am using Visual Studio 2022 Community and my template files are not located in the installation folder but in the `AppData`  folder:
`%userfolder%\AppData\Local\Microsoft\VisualStudio\17.0_6e63176c\Extensions\jxnhm1ga.wt4\Templates`
