### ISSUE TITLE
Extension Disabled

### ISSUE THREAD

**Issue by Andy65** [madskristensen/AddAnyFile#36]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 3.5.110

### Description
I keep enabling this extension and it keeps getting disabled by something else and I have no idea what or why.

### Steps to recreate
No specific steps - this presumably is a problem for you or it is not.

### Current behavior
The extension keeps getting disabled.

### Expected behavior
When enabled the extension should stay enabled until I manually disable it.

**Comment by stephenismay** [comment]
Same problem for me:

Microsoft Visual Studio Community 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
Installed Version: Community

Microsoft Visual Studio Tools for Applications 2015   00322-20000-00000-AA332
Visual Basic 2015   00322-20000-00000-AA332
Visual C# 2015   00322-20000-00000-AA332
Visual C++ 2015   00322-20000-00000-AA332
Add New File   3.5
Application Insights Tools for Visual Studio Package   7.1.00719.1
ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
Azure App Service Tools v2.9.1   14.0.20622.0
Azure Data Lake Node   1.0
Azure Data Lake Tools for Visual Studio   2.0.6000.0
Common Azure Tools   1.8
JavaScript Language Service   2.0
JavaScript Project System   2.0
Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft Azure HDInsight HQL Service   2.0.6000.0
Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40701.9
NuGet Package Manager   3.5.0
Open Command Line   2.1.175
PreEmptive Analytics Visualizer   1.2
Python Tools for Visual Studio   2.2.40623.00
Python Tools for Visual Studio - Django Integration   2.2.40623.00
Python Tools for Visual Studio - Profiling Support   2.2.40623.00
SQL Server Analysis Services   13.0.1605.88
SQL Server Data Tools   14.0.60629.0
Microsoft SQL Server Integration Services Designer Version 13.0.1601.5
SQL Server Reporting Services   13.0.1605.88
ToolWindowHostedEditor   1.0
TypeScript   1.8.36.0
Web Compiler   1.11.319
Web Essentials 2015.3   3.0.230

**Comment by kentcb** [comment]
Yep, came here to report exactly this. It seems to be a recent problem, perhaps since the latest update (3.5.111). It is not even possible to uninstall and reinstall it (it still shows up as disabled after attempting to uninstall).

```
Microsoft Visual Studio Enterprise 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA203
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Microsoft Visual Studio Tools for Applications 2015   00322-80000-00000-AA203
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-80000-00000-AA203
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA203
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA203
Microsoft Visual C++ 2015

Visual F# 2015   00322-80000-00000-AA203
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA203
Windows Phone SDK 8.0 - ENU

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.1   14.0.20622.0
Azure App Service Tools v2.9.1

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.1.0000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

File Icons   1.3
Adds icons for files that are not recognized by Solution Explorer

HideMenu   1.0
Hides the Visual Studio main menu, similar to Windows Explorer and Internet Explorer

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Hive Query Language Service   2.1.0000.0
Language service for Hive query

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40518.2

NCrunch   
Continuous Testing Tool for .NET
Copyright © 2010-2016 Remco Software Ltd

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   13.0.1605.88
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1605.88

SQL Server Data Tools   14.0.60629.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1605.88
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1605.88

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Trailing Whitespace Visualizer   2.5.80
Keeps your code files clean by making it easier than ever to identify and remove any trailing whitespace

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25420.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   4.1.2.18 (fcbe082)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.1.2.21 (1cf254d)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   9.8.2.22 (f37444a)
Visual Studio extension to enable development for Xamarin.iOS.
```

**Comment by madskristensen** [comment]
This is a bug in Visual Studio. Please try to delete the MEF cache like so: https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd
