### ISSUE TITLE
Add 2 files in VS 2015

### ISSUE THREAD

**Issue by mrchief** [madskristensen/AddAnyFile#4]
Noticed this in a new ASP.Net vNext project. When I right click on a folder and add a new file, the file gets added to both the selected folder and the solution root.

**Comment by madskristensen** [comment]
Yes, this is a bug in the Common Project System in VS that ASP.NET 5 is using. It's supposed to be fixed when VS2015 RTM is shipped

**Comment by madskristensen** [comment]
This has been fixed in version 1.9
