### ISSUE TITLE
Crash when trying to add file on project

### ISSUE THREAD

**Issue by emsteenbrink** [madskristensen/AddAnyFile#40]
### Installed product versions
- Visual Studio: Community 2015 update 3 
- This extension: 3.5.116

### Description
When right-clicking on the project and selecting Add->New empty file, I get a "Microsoft Visual Studio has stopped working" 
Same goes when selecting the project and pressing ctrl-F2. 
When doing the same on the wwwroot folder inside the project, It seems to be working fine.

**Comment by madskristensen** [comment]
Fixed and new version on its way to the gallery
