### ISSUE TITLE
Error Message 0x80004005

### ISSUE THREAD

**Issue by TFreudi1** [madskristensen/AddAnyFile#47]
### Installed product versions
- Visual Studio: VS2017 Community Version 15.2(26430.13)
- This extension: 3.5.129

### Description
16.06.2017 09:34:31: System.Runtime.InteropServices.COMException (0x80004005): Beim Aufruf einer COM-Komponente wurde ein HRESULT E_FAIL-Fehler zurückgegeben.
   bei EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   bei MadsKristensen.AddAnyFile.AddAnyFilePackage.<MenuItemCallback>d__2.MoveNext() in C:\projects\addanyfile\src\AddAnyFilePackage.cs:Zeile 114.

### Steps to recreate
Install in ViS via "Extension And Updates" - "Online" - "Visual Studio Marketplace"
Open a .NET project, add a "test.html" file wirh "New Empty File"

### Current behavior
The file is correctly created but the message under ###Description appears in output window of VS

### Expected behavior
No error message

**Comment by Structed** [comment]
I can confirm the issue, though it seems to have no major impact.

`14.12.2017 16:48:50: System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at MadsKristensen.AddAnyFile.AddAnyFilePackage.<MenuItemCallback>d__2.MoveNext() in C:\projects\addanyfile\src\AddAnyFilePackage.cs:line 114`

**Comment by SamuelEnglard** [comment]
Can confirm this is still happening as for VS 15.9.6 and extension version 3.5.136.

**Comment by henrik-jensen** [comment]
Also confirmed with VS 2019 16.4.0 Preview 1.0

Version info:
```
Microsoft Visual Studio Community 2019 Preview
VisualStudio.16.Preview/16.4.0-pre.1.0+29319.158
Add New File   3.5.134
```

Output:
```
29-09-2019 21:43:05: System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at MadsKristensen.AddAnyFile.AddAnyFilePackage.<ExecuteAsync>d__2.MoveNext() in C:\projects\addanyfile\src\AddAnyFilePackage.cs:line 115

```
