### ISSUE TITLE
Menu item doesn't work and file not added to solution

### ISSUE THREAD

**Issue by Gruntfuggly** [madskristensen/AddAnyFile#5]
Selecting the New Empty File... option from the context menu does nothing.

If I use the keyboard shortcut the file is created in the correct folder, but it is not added to the solution or opened in the editor. 

Is there somewhere I can get a log file from?

**Comment by madskristensen** [comment]
What type of project do you have? MVC, Console app, winforms project or...?

"Selecting New Empty File" from where? The solution node, on a folder, on a solution folder or...?

What version of VS?

**Comment by Gruntfuggly** [comment]
Hi there - it's a C++ Win32 GUI app with Win32 static libraries. 

I've tried the menu option from Solution folders folders and filters, but neither pop up the window.

It's VS 2013.
