### ISSUE TITLE
JSON file encoding should be UTF-8-BOM (for ASP.NET Core Projects)

### ISSUE THREAD

**Issue by nstohler** [madskristensen/AddAnyFile#51]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 3.5.129

### Description
JSON file encoding should be UTF-8-BOM (for ASP.NET Core Projects).

### Current behavior
When adding a JSON file using this extension, I get an ANSI encoded file. Using this file with special characters (äöü) as a configuration file, those characters are not read correctly then. Using Notepad++ to change the encoding of the JSON file to UTF-8-BOM (and manually converting the special characters) fixes the problem. 
When adding a JSON file the VS-way (add->new item->json), the encoding of the file is set correctly and there are no problems when reading the configuration.

### Expected behavior
Add the JSON file with the UTF-8-BOM encoding.

**Comment by perennialmind** [comment]
The JSON spec is explicit: compliant files "MUST NOT add a byte order mark". I usually cope with this kind of issue with EditorConfig files. Alternatively, recent versions of Windows allow you switch your ANSI locale to UTF-8, so can avoid Windows-1252 contamination entirely.
```
[*.json]
charset = utf8
```
https://tools.ietf.org/html/rfc7159#section-8.1
https://editorconfig.org/

**Comment by nstohler** [comment]
Thanks for clearing that up.
