### ISSUE TITLE
Commas in filenames create multiple files

### ISSUE THREAD

**Issue by paulomorgado** [madskristensen/AddAnyFile#52]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 3.5.129

### Description
Using commas in file names creates multiple files.

**Class{T1,T2,T3}.cs** is a valid file name and a pattern often used.

### Steps to recreate
1. Shift+F2
2. **Class{T1,T2,T3}.cs**

### Current behavior
Creates files:
* Class{T1
* T2
* T3}.cs

### Expected behavior
Creates file **Class{T1,T2,T3}.cs**

**Comment by CTBT** [comment]
isn´t that a feature ?
