### ISSUE TITLE
[Bug] Grey text on grey background (dark theme)

### ISSUE THREAD

**Issue by TobiasSekan** [madskristensen/AddAnyFile#58]
### Installed product versions
- Visual Studio: **2017** Professional Version 15.9.0 Preview 1.0
- This extension: **3.5.134**

### Description
When currently open the dialogue window I get this
(I use the dark theme in visual studio)
![2018-09-11 08_42_13-add new file](https://user-images.githubusercontent.com/17874713/45342699-026e2300-b59f-11e8-8afc-c9bbe830e463.png)

**Comment by spottedmahn** [comment]
FYI, sometimes it works and sometimes it doesn't.  I can't reliably repro it.

**Comment by TobiasSekan** [comment]
Okay,
I think we can close this

**Comment by spottedmahn** [comment]
I think we should keep it open.  It just happened to me again...

What debug info can I provide when it happens?

**Comment by spottedmahn** [comment]
Hi @TobiasSekan - can you re-open?  Still a problem for me, thanks!

**Comment by spottedmahn** [comment]
Hi @madskristensen - can you re-open this?  Still a problem... thanks

**Comment by spottedmahn** [comment]
thanks @madskristensen 👍
