### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by Bartmax** [madskristensen/AddAnyFile#6]
This extension is beautiful and should be added into vs 2015 RTM.

I like the templates feature and for .cs files it would be great if it created something more like

```
using System;

namespace {{DefaultNamespace}}.{{Path}} {
    public class {{FileName}} {
        $
    }
}
```
I would also make the templating not only on the extension. For example, if the file name starts with a capital I and the second letter is uppercase I will make it an interface
```
namespace {{DefaultNamespace}}.{{Path}} {
    public interface {{FileName}} {
        $
    }
}
```
if it's suffix is Controller, like SomeController.cs I would love to see the controller template, and more patterns.

Also some known files like gulp-config or bower.json, config.json all can have a different template not only based on file extension.

Lastly, when/how can one start helping on the templates ? I'm really exciting to see this as the default file new ;)

**Comment by madskristensen** [comment]
I think the we should see if we can invoke the existing templates directly. They already come with support for namespace, class names etc. It was always on my agenda to do that, but I never got around to do it. 

That means we have to add 2 pieces of logic:

1. Invoke existing item templates
2. Map file names with existing templates

**Comment by Bartmax** [comment]
Using the existing templates would be awesome!! Doesn't sound as an easy task tho.

**Comment by hakenr** [comment]
+1 for this idea

**Comment by sameera** [comment]
@Bartmax @madskristensen , I've implemented the support for VS templates and added neat pattern based templating feature. I'm preparing the Pull Request at the moment. Here's a heads-up on how this feature will work:
The plugin now has a map of (regex) patterns, and a corresponding VS template. 
**c:**MyClass *generates a C# class named MyClass*
**i:**MyInterface *generates a C# interface named MyInterface*
Names with **.cs** extension generates a C# code file with namespace declaration
Names with **.js** extension generates a JavaScript file 

Ideally, in the future, there'll be a VS Options dialog page to configure the patterns. But, above patterns should cover most of the requirements :)

**Comment by sameera** [comment]
... And if the pattern didn't match (e.g. README.md), the plugin goes through the existing logic to create the file.

**Comment by sameera** [comment]
Pull #9 is now updated with the following features:

* `I<name>.cs` for C# Interfaces
* `<name>cs` defaults to C# classes
* `e:<name>.cs` for blank C# files (with namespaces)
* All available patterns can be modified by updating the Patterns.json file in VisualStudio.AddNewFile folder in side %AppData%

Hope others would find these changes useful :)

**Comment by mrahhal** [comment]
No status on this yet? This is really the only thing preventing me from hitting Shift+F2 everytime instead of "Context Menu"->"Add New Item" (sometimes I do it anyway). Isn't #9 already complete?

**Comment by sameera** [comment]
#9 is not merged yet. 
You could build from my fork [here](https://github.com/sameera/AddAnyFile).

As I've been actively using this fork myself, I've added few minor features and fixes since the PR #9. Please see the [commit history](https://github.com/sameera/AddAnyFile/commits/master) for these changes.

**Comment by mrahhal** [comment]
Ahh thanks! Will do.

**Comment by mrahhal** [comment]
@sameera nice work. Though I'm getting a

```
The reference "System" could not be added to the project. This wizard will continue to run, but the resulting project may not build properly.
```

dialog after I add the file. The file gets added anyway so all's good. I'm in a dnx project so that may be related.

**Comment by sameera** [comment]
I'm not familiar with DNX projects myself; so, I'm not sure why this you are getting this error. I haven't seen this error myself, so It could be related to project type as you said.

Perhaps [this question on stackoverflow](http://stackoverflow.com/questions/20767932/the-namespace-system-could-not-be-added-to-the-project) may help?

**Comment by madskristensen** [comment]
DNX is the new ASP.NET 5 projects.

**Comment by sameera** [comment]
I see that the original code had a check to avoid adding files to ASP.net 5 projects (the same still exists if the code go through the non-templated path). 
Is there a known compatibility issue in adding files to these projects?

**Comment by madskristensen** [comment]
Those projects will automatically add the files to them, so no need to add them from this extension

**Comment by mrahhal** [comment]
@madskristensen  I'm not sure if you're aware, but templates are not working with Asp.Net Core projects. Files are added, but they're always empty. Is there a known bug or does templating work differently under this type of project?

I think that when I was using a custom build from @sameera's fork templates were correctly applied but with an erorr (that does no harm).

**Comment by madskristensen** [comment]
Just fixed it. Try it out in the latest CI build from here http://vsixgallery.com/extension/2E78AA18-E864-4FBB-B8C8-6186FC865DB3/

**Comment by mrahhal** [comment]
Awesome! Everything is working perfectly now.
