### ISSUE TITLE
Feature: Dark theme

### ISSUE THREAD

**Issue by maraf** [madskristensen/AddAnyFile#62]
It would be lovely if dialog respects selected VS theme.

I have done some research and it seems that simply setting `Background` and `Foreground` properties using `DynamicResource` to keys in `VsBrushes` (`ToolWindowBackgroundKey` and `ToolWindowTextKey`) can do the trick. 

Can I make a PR?

**Comment by jflepp** [comment]
👍

**Comment by madskristensen** [comment]
Absolutely, that would be awesome
