### ISSUE TITLE
VS2019 16.6.0 - Extension stopped working?

### ISSUE THREAD

**Issue by fudgeboy2000** [madskristensen/AddAnyFile#70]
### Installed product versions
- Visual Studio: 2019 Enterprise 16.6.0
- This extension: 3.5.140

### Description
After the upgrade to 16.6.0 last week, Add New File no longer works.  Can't see any error messages or failures anywhere - it just isn't on the context menu, and Shift-F2 does nothing.

### Steps to recreate
Upgrade VS to 16.6.0

### Current behavior
Add New File no longer works.

### Expected behavior
Add New File should work.

I understand that all sounds lame.  I've tried disabling/enabling, uninstalling the extension and re-adding, and deleting the ComponentModelCache folder.

**Comment by chucker** [comment]
I'm fairly sure I used it in the 16.6 previews. I also just successfully used it in 17.1 preview 1. So my guess is it'll work fine in 16.6 final.

Interestingly, though, my extension gives 3.5.138 as its version. Maybe you got a broken update?

**Comment by fudgeboy2000** [comment]
I was using 3.5.138, with the same issue, and tried 3.5.140 from the nightly build to see if it helped.  It didn't.  But I've installed a fresh VS2019 16.6 on a different laptop and Add New File works fine there, so it must be something on my main dev machine specifically.  I don't know how to debug that, but it looks to be specific to me now so I'll close.  Many thanks!
