### ISSUE TITLE
Custom keyboard shortcut

### ISSUE THREAD

**Issue by johnknoop** [madskristensen/AddAnyFile#72]
### Installed product versions
- Visual Studio: 2019
- This extension: latest

Any chance you would enable us to change the keyboard shortcut?

**Comment by johnknoop** [comment]
@madskristensen that's where I've been looking, but I'm not sure what to search for. The phrase "AddAnyFile" doesn't give any hits.

**Comment by papalanga** [comment]
@johnknoop Try searching for "NewEmptyFile".

**Comment by johnknoop** [comment]
Thanks

**Comment by oscarsun72** [comment]
> NewEmptyFile
> @johnknoop Try searching for "NewEmptyFile".

it works Thanks a lot.
其實在要設定快速鍵的地方按下Alt+F1應該也會顯示這組快捷鍵是被指定給什麼指令了，再由該指令名稱去查找，應該就可以了。In fact, pressing Alt+F1 at the place where you want to set the shortcut keys should also display what command this group of shortcut keys is assigned to, and then search by the command name, it should be fine. 感恩感恩　讚歎讚歎　南無阿彌陀佛

**Comment by lawrence-laz** [comment]
The name is very hard to find. I would expect to be able to search it by package name.
