### ISSUE TITLE
Support solution items

### ISSUE THREAD

**Issue by chucker** [madskristensen/AddAnyFile#74]
### Installed product versions
- Visual Studio: 2019 16.8p1
- This extension: 3.5.138

### Description
You can hit <kbd>Shift</kbd>-<kbd>F2</kbd> on the project, but you can't on the solution.

This would be useful to create special files like `NuGet.config`, `dotnet-tools.json`, `.editorconfig`, etc.

**Comment by IainCoSource** [comment]
The menu guid would be `IDG_VS_CTXT_SOLUTION_ADD_ITEM` the next task would be to adjust the helper method to figure out the current selection. Maybe using `IVsMonitorSelection2`...
