### ISSUE TITLE
[Request] When creating a C# file, use file-scoped namespace declaration if possible

### ISSUE THREAD

**Issue by ryanbuening** [madskristensen/AddAnyFile#90]
In C# 10 we can now use [a new form of the namespace declaration](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration) to declare that all subsequent declarations are members of the declared namespace:

`namespace MyNamespace;`

Is this extension able to detect the version of C# being used and use this new syntax?

**Comment by nathan130200** [comment]
up

**Comment by kelps** [comment]
I understand we can change the templates, but that is not a great solution because file scoped namespaces are only supported starting with .net 6. If not all your the projects in your organization are .net 6, changing the template will cause problems when working on pre-net6 projects.

On the other hand, to be able to "properly" do this, a simple template isn't enough, because if you want to detect and respect this setting, you should also detect and respect other style settings, both in .editorconfig and in VS.

Adding a file with the stock "Add > New item..." menu in VS2022 does apply and respect your settings. I was thinking that one "simple" solution in this case would be to run "dotnet format style" for that file, but I just tried and it only works for solutions and projects, not individual files. I REALLY like this extension and I use it a LOT. It would be excellent if this feature was implemented...

**Comment by nathan130200** [comment]
I agree also, specially with WinForms templates.

**Comment by timheuer** [comment]
> I understand we can change the templates, but that is not a great solution because file scoped namespaces are only supported starting with .net 6. If not all your the projects in your organization are .net 6, changing the template will cause problems when working on pre-net6 projects.

One clarification, this is not a .NET6 thing, but a C#9 thing, but still agree with @kelps that changing the base item templates is not ideal.

> On the other hand, to be able to "properly" do this, a simple template isn't enough, because if you want to detect and respect this setting, you should also detect and respect other style settings, both in .editorconfig and in VS.
> 
> Adding a file with the stock "Add > New item..." menu in VS2022 does apply and respect your settings. I was thinking that one "simple" solution in this case would be to run "dotnet format style" for that file, but I just tried and it only works for solutions and projects, not individual files. I REALLY like this extension and I use it a LOT. It would be excellent if this feature was implemented...

Just added a draft PR #101 to accommodate/try to fix this.

**Comment by kelps** [comment]
Ok, I am impressed! Looks like a very simple fix. I really hope there are no side effects. There are 3 extensions I use almost every day and this is one of them. 

The other ones are Open Command Line [ Alt + Space ] and Extension Manager. In my view, all 3 should already by built-in features in VS.

**Comment by timheuer** [comment]
If interested in this capability see the PR #101 to follow the scenarios kind of breaking with this change.  Might be an issue with Roslyn or VS -- not sure yet, but tracking the issue there.  Indeed subfolders and caret position are affected with this behavior.

**Comment by timheuer** [comment]
If anyone wants to kick the change around -- fixed the project issue and the PR is updated if you want to build/run it with the change.

**Comment by timheuer** [comment]
Realized a build from this is available: https://ci.appveyor.com/project/madskristensen/addanyfile/builds/41895811/artifacts

**Comment by ryanbuening** [comment]
The build from appveyor seems to be working for me. 

The only thing that I would change is not including the `System` usings (when creating a class, interface, etc.) as implicit usings are turned on by default now in .NET 6, but that is probably a different topic.

Thanks!

**Comment by madskristensen** [comment]
This should now work and you can help test it using the latest [CI build](https://www.vsixgallery.com/extension/d48e8f25-661b-4970-8b66-03f051ba5fc3).

**Comment by timheuer** [comment]
> The only thing that I would change is not including the `System` usings (when creating a class, interface, etc.) as implicit usings are turned on by default now in .NET 6, but that is probably a different topic.

Yeah I wouldn't change that.  Item templates aren't versioned specific so it's better to rely on editorconfig/refactoring/code-cleanpu post-rules IMO.

**Comment by kelps** [comment]
You guys are amazing. I'll try it tomorrow.

**Comment by tiesmaster** [comment]
@madskristensen I've been using the CI build for the last couple of days, and it's working like a charm. Really amazing man, thank you!
